language: php
 
php:
  - 7.2
  - 7.3
 
before_script:
  - composer install --prefer-source --no-interaction --no-dev
 
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
